# Air pollution NOx, NO2 and O3

In [1]:
from IPython.display import display, Markdown
import sys
import os
sys.path.append(os.path.abspath('../../../../scripts/'))
from data_doc_helper import PlaceDataSet as DS, last_modified
last_modified()

>Last modified: 23 Jul 2025

In [2]:
display(Markdown('<div style="background-color: rgba(0, 178, 169, 0.3); padding: 5px; border-radius: 5px;"><strong>UK LLC provides high-resolution national exposure surfaces for NO₂ and O₃ in England and Wales.</strong></div>'))

<div style="background-color: rgba(0, 178, 169, 0.3); padding: 5px; border-radius: 5px;"><strong>UK LLC provides high-resolution national exposure surfaces for NO₂ and O₃ in England and Wales.</strong></div>

In [3]:
display(Markdown('<div style="background-color: rgb(229, 106, 84, 0.3); padding: 5px; border-radius: 5px;"><strong>More information about this dataset is available <a href="Understanding_air_pollution_o3.html" target="_blank">here.</a></strong></div>'))

<div style="background-color: rgb(229, 106, 84, 0.3); padding: 5px; border-radius: 5px;"><strong>More information about this dataset is available <a href="Understanding_air_pollution_o3.html" target="_blank">here.</a></strong></div>

## Hybrid Air Dispersion Exposure System (HADES)

The exposure surfaces were created using the HADES: Hybrid Air Dispersion Exposure System modelling framework, which combines dispersion modelling with satellite-derived estimates of background concentrations, land cover, and a 3-D representation of buildings, in a statistical calibration framework.

These datasets contain national-scale outdoor nitrogen dioxide (NO2) and ozone (O3) exposure surfaces for England and Wales in 2018, 2019, and 2020 at very high spatial resolutions (10m and 100m). Participants residential addresses or postcodes are linked to one of the 10m x 10m cells. These exposures are also summarised for the 2021 UK Census communities in England and Wales using area-weighted sampling (i.e., zonal average). These values represent community background exposures for Census Output Area (COA), Lower Layer Super Output Area (LSOA) and Middle Layer Super Output Area (MSOA).

Modelling explained 77-79% for NO2 and 87-89% for O3 of the variability in hourly-annual average concentrations and was robust to changes in NOx emissions during the COVID pandemic.

## 1. Summary

In [4]:
display(Markdown('### HADES_estimates_england_wales_hh'))

### HADES_estimates_england_wales_hh

In [5]:
DS("HADES_estimates_england_wales_hh").info_table()

UnboundLocalError: cannot access local variable 'df_ds' where it is not associated with a value

In [6]:
display(Markdown('### air_pollution_pc'))

### air_pollution_pc

In [7]:
DS("air_pollution_pc").info_table()

## 2. Variables

In [8]:
display(Markdown('### air_pollution_hh'))

### air_pollution_hh

In [9]:
DS("air_pollution_hh").variable_table()

In [10]:
display(Markdown('### air_pollution_pc'))

### air_pollution_pc

In [11]:
DS("air_pollution_pc").variable_table()

## 3. Metrics

In [12]:
display(Markdown('TBC'))

TBC

## 4. Version History

In [13]:
display(Markdown('TBC'))

TBC

## 5. Documentation

In [14]:
DS("air_pollution_pc").documentation()

We are currently building a documentation storage system which will host useful documents related to datasets and data owners. We will surface these documents on Guidebook.

## 5. Useful Syntax

In [15]:
DS("air_pollution_pc").useful_syntax()

Below we will include syntax that may be helpful to other researchers in the UK LLC TRE. For longer scripts, we will include a snippet of the code plus a link to the [UK LLC GitHub](https://github.com/UKLLC) repository where you can find the full scripts.