In [1]:
# define freeze number
freeze_num = 3
# import packages
import pandas as pd, sys
from IPython.display import HTML, display, Markdown
# create instance of freeze class
fp = 'S:/UKLLC - UKLLC Databank/UKLLC Systems/programs/quarterly'
sys.path.insert(0, fp)
import freeze_helper as fh
frehelp = fh.FreezeHelper(freeze_num)

# Freeze number 3 dated February 2023

Due to the UK LLC pooled sample being dynamic and the denominator changing over time, the UK LLC establishes a 'data freeze' of the pooled sample each quarter. Approved users are provisioned data against a set freeze which fixes their denominator at the start of their project and this remains fixed throughout the course of the project.

### Table 1: Participants enrolled in LPS and included in the UK LLC resource 

Variation in contribution rates between LPS is mostly due to differences in fair processing. UK LLC continues to work with LPS to establish the governance permissions necessary to maximise the number of enrolled participants in the UK LLC resource.

In [ ]:
display(frehelp.style_table(frehelp.get_table('table1')))

### Table 1 exclusions: The total number of participants not sent to UK LLC with reason for exclusion

In [ ]:
display(frehelp.style_table(frehelp.get_exclusions()))

***Footnotes with further details about exclusion criteria***

(i) & (ii) UK LLC does not prohibit LPS from sending data for participants who have died. However, some LPS have policies which preclude these participants from inclusion in the resource. Data for participants who died on or after January 1, 2020 are particularly important for COVID-19 research, and so LPS were requested to send these data where possible.

(v) Participants who have dissented from linkage can still be included in the UK LLC resource, with permission flags set accordingly. However, some LPS policies preclude participants from inclusion.

Where a participant was excluded for more than one reason, LPS were asked to count participants once using the exclusion hierarchy (i-vii).

Information presented in Table1 was provided by the LPS at the latest quarterly File1 update corresponding with the freeze name printed at the top of this notebook.

### Table 2: Participants in the UK LLC with permission to link to NHS England and their legal basis 

Permission flags are set at a participant level or at an LPS level giving participants or LPS control over which linkages are established or removed. NHS England operates the National Opt Out (NOO) scheme, where individuals can request that their health record is not shared for research purposes. Where explicit and informed consent is in place, the NOO is overwritten. Where opt-out consent approaches are used in conjunction with Section 251 (s251) of the NHS Act 2006, then NOO is fully respected and no records will be accessed. The current NOO rate is 5.4% of the population; information on NOO rates can be found on the NHS England website<sup>1</sup>. For this reason, the UK LLC anticipates lower linkage rates where s251 is used. 

<p style='font-size: 12px;'><sup>1</sup>digital.nhs.uk/services/national-data-opt-out</p>

In [ ]:
table2 = display(frehelp.style_table(frehelp.get_table('table2')))

***Footnotes***

Participants in SABRE do not currently permit linkage to NHS England and therefore do not feature in Table 2.

Participants in GENSCOT and NICOLA do not currently have permission to link to NHS England due to governance issues and geographical limitations and therefore also do not feature in Table 2.